spring:
  cache:
    redis:
      time-to-live: 3600000
  session:
    timeout: 43200m
  application:
    name: api-gateway
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        user-service-url: http://localhost:8081
        company-service-url: http://localhost:8082
        storage-service-url: http://localhost:8083
        mail-service-url: http://localhost:8084
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            provider: oidc-client-provider
            client-id: oidc-client
            client-authentication-method: client_secret_basic
            client-secret: secret
            scope:
              - openid
              - profile
            authorization-grant-type:  authorization_code
        provider:
          oidc-client-provider:
            issuer-uri: http://localhost:9000
server:
  port: 8080
  forward-headers-strategy: framework
logging:
  level:
    org.springframework:
      session: debug
      security: debug