server:
  port: 8082
  forward-headers-strategy: framework
spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5433/companydb
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver